name: "radicale"

services:
  dav:
    image: tomsquest/docker-radicale
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    deploy:
      resources:
        limits:
          memory: 256M
          pids: 50
    restart: unless-stopped
    volumes:
      - ./data/dav/data:/data
      - ./state/dav/config:/config:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
