name: "immich"

x-environment: &shared-environment
  TZ: "Europe/Moscow"
  DB_PASSWORD: ${DATABASE_PASSWORD:?error}
  DB_USERNAME: ${DATABASE_USERNAME:?error}
  DB_DATABASE_NAME: "immich"

x-attributes: &shared-attributes
  labels:
    - "com.centurylinklabs.watchtower.enable=false"

services:
  server:
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ./data/server/data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    environment:
      <<: *shared-environment
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
      - proxy
      - default

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ./state/machine-learning/cache:/cache
    environment:
      <<: *shared-environment
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
      - default

  redis:
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    <<: *shared-attributes
    networks:
        - default

  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      <<: *shared-environment
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ./data/database/data:/var/lib/postgresql/data
    <<: *shared-attributes
    healthcheck:
      test: >-
        pg_isready --dbname="$$DB_DATABASE_NAME" --username="$$DB_USERNAME" || exit 1;
        Chksum="$$(psql --dbname="$$DB_DATABASE_NAME" --username="$$DB_USERNAME" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: unless-stopped
    networks:
        - default

networks:
  default:
    driver: bridge
  proxy:
    external: true
