name: "minecraft"

x-environment: &shared-environment
  TZ: "Europe/Moscow"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./state/nginx/data:/etc/nginx
      - ./data/alpha/data/bluemap/web:/var/www/bluemap:ro
    networks:
      - proxy

  router: 
    image: itzg/mc-router
    restart: unless-stopped
    environment:
      MAPPING: |
        mcr.ermnvldmr.com=alpha:25565
    ports:
      - 25565:25565
    networks:
      minecraft:
        ipv4_address: 10.1.2.2

  alpha:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.1"
      MEMORY: "4G"
    volumes:
      - ./data/alpha/data:/data
    networks:
      minecraft:
        ipv4_address: 10.1.2.3

  backup:
    image: itzg/mc-backup
    depends_on:
      alpha:
        condition: service_healthy
    environment:
      <<: *shared-environment
      BACKUP_INTERVAL: "0"
      RCON_HOST: alpha
      INITIAL_DELAY: 0
      EXCLUDES: "*.jar,cache,logs,*.tmp,bluemap"
    volumes:
      - ./data/alpha/data:/data:ro
      - ./backup/alpha/data:/backups
    networks:
      minecraft:
        ipv4_address: 10.1.2.4

networks:
  minecraft:
    name: "minecraft"
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.2.0/24
  proxy:
    external: true
